[[redirects]]
  from = "/api/*"
  to = "http://localhost:8090/api/:splat"
  status = 200

[[redirects]]
  from = "/resources/*"
  to = "http://localhost:8090/resources/:splat"
  status = 200


[[redirects]]
  from = "/pusher/*"
  to = "http://202.31.202.150:80/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  